services:
  mkr-agent:
    image: none
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9099:9099
    volumes:
      - .:/app

networks:
  swarm-internal:
    external: false
    driver: bridge