name: Build and push Docker image

on:
  push:
    branches: ["main"]
    # Facultatif : ne d√©clencher que si Dockerfile ou config change
    # paths:
    #   - "Dockerfile"
    #   - ".github/workflows/docker-ghcr.yml"
    #   - "src/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }} # org/repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ github.token }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t $REGISTRY/${{ env.IMAGE_NAME }}:latest \
            -t $REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest
          docker push $REGISTRY/${{ env.IMAGE_NAME }}:${{ github.sha }}
